- name: 'test play'
  hosts: dp1
  connection: local
  vars:
    domain: default
  tasks:
    - name: Save domain config
      community.datapower.action:
        domain: "{{ domain }}"
        body:
          SaveConfig: {}



