- name: 'test play'
  hosts: dp1
  connection: local
  vars:
    domain: default
  tasks:
    #- name: Get details on available actions in the chosen domain
    #  community.datapower.action_info:
    #    domain: default
    - name: Get details on SaveConfig action
      community.datapower.action_info:
        domain: default
        action: SaveConfig
    - name: Save snafu domain
      community.datapower.action:
        domain: snafu
        action: SaveConfig
    - name: Reset snafu domain
      community.datapower.action:
        domain: snafu
        action: ResetThisDomain