- name: 'Demo apply_conf'
  hosts: dp1
  connection: local
  tasks:
    - name: Create 
      community.datapower.apply_config:
        state: present
        domain: default
        config: 
          CryptoValCred:
            name: valcred
            mAdminState: enabled
            Certificate:
            - value: Test1
            - value: Test2
            CertValidationMode: legacy
            UseCRL: 'off'
            RequireCRL: 'on'
            CRLDPHandling: ignore
            ExplicitPolicy: 'off'
            CheckDates: 'on'
    
    - name: Unquiesce DP after the change
      community.datapower.action:
        domain: default
        action: SaveConfig
