- name: 'test play'
  hosts: datapower
  connection: local
  vars: 
    ansible_connection: httpapi
    ansible_httpapi_port: 5554
    ansible_httpapi_use_ssl: yes
    ansible_network_os: datapower
    ansible_user: admin
    ansible_httpapi_password: admin
    ansible_httpapi_validate_certs: false
  tasks:
  - name: Get default domain config
    community.datapower.get:
      domains:
      - default
      object_class: Domain    
      name: default

