- name: 'Demo apply_conf'
  hosts: dp1
  connection: local
  vars:
  tasks:
    - name: Apply a change to valcred
      community.datapower.apply_config:
        state: present
        domain: default
        name: valcred
        class_name: CryptoValCred
        config: 
          mAdminState: enabled
          UseCRL: "off"
          Certificate: 
            value: Test1

    - name: get valcred
      community.datapower.get_config:
        domain: default
        class_name: CryptoValCred
        name: valcred
    - name: save domain
      community.datapower.action:
        domain: default
        action: SaveConfig