- name: 'test create_conf play'
  hosts: dp1
  connection: local
  vars:
    domain: default
  tasks:
    - name: Create certificate
      community.datapower.create_conf:
        domain: "{{ domain }}"
        body:
          CryptoCertificate:
            name: Test2
            mAdminState: enabled
            Filename: cert:///webgui-sscert.pem
            PasswordAlias: 'off'
            IgnoreExpiration: 'off'

    - name: Modify CryptoValCred to add the cert object, target the list to minimize the change footprint.
      community.datapower.mod_conf:
        domain: "{{ domain }}"
        class_name: CrytoValCred
        name: valcred
        obj_field: Certificate
        body: >
          { "Certificate": [
                  {
                      "href": "/mgmt/config/default/CryptoCertificate/Test1",
                      "value": "Test1"
                  }
            ]
          }
          
 

