- name: 'test play'
  hosts: dp1
  connection: local
  vars:
    domain: default
  tasks:
    - name: Modify ValidationCredential to delete cert object
      community.datapower.mod_conf:
        domain: "{{ domain }}"
        body: >
          {
            "CryptoValCred": {
              "CRLDPHandling": "ignore",
              "CertValidationMode": "legacy",
              "Certificate": [
                  {
                      "href": "/mgmt/config/default/CryptoCertificate/Test1",
                      "value": "Test1"
                  }
              ],
              "CheckDates": "on",
              "ExplicitPolicy": "off",
              "InitialPolicySet": "2.5.29.32.0",
              "RequireCRL": "off",
              "UseCRL": "on",
              "mAdminState": "enabled",
              "name": "valcred"
            }
          }

    - name: Delete Object
      community.datapower.del_conf:
        domain: "{{ domain }}"
        class_name: CryptoCertificate
        name: Test2




