- name: 'test play'
  hosts: dp1
  connection: local
  vars:
    domain: default
  tasks:
    - name: Delete Object
      community.datapower.del_conf:
        domain: "{{ domain }}"
        class_name: CryptoCertificate
        name: Test2




