- name: 'test play'
  hosts: dp1
  connection: local
  vars: 
    ansible_connection: httpapi
    ansible_httpapi_port: 5554
    ansible_httpapi_use_ssl: yes
    ansible_network_os: community.datapower.rest_mgmt
    ansible_user: admin
    ansible_httpapi_password: admin
    ansible_httpapi_validate_certs: false
  tasks:

    - name: Export object configuration
      community.datapower.export:
        domain: default
        body:
          Export:
            Format: JSON
            UserComment: comments
            AllFiles: 'off'
            Persisted: 'off'
            IncludeInternalFiles: 'off'
            Object:
              - name: valcred
                class: CryptoValCred
    - name: Load object configuration
      community.datapower.load_conf:
        domain: default
        body:
          LoadConfiguration:
            CryptoValCred:
              CRLDPHandling: ignore
              CertValidationMode: legacy
              Certificate:
                - Test1
                - Test2
              CheckDates: 'on'
              ExplicitPolicy: 'off'
              InitialPolicySet: 2.5.29.32.0
              RequireCRL: 'off'
              UseCRL: 'on'
              mAdminState: enabled
              name: valcred

