- name: 'test play'
  hosts: dp1
  connection: local
  vars:
    domain: default
  tasks:
    - name: Export object configuration
      community.datapower.export:
        domain: "{{ domain }}"
        body:
          Export:
            Format: JSON
            UserComment: comments
            AllFiles: 'off'
            Persisted: 'off'
            IncludeInternalFiles: 'off'
            Object:
              - name: valcred
                class: CryptoValCred
    - name: Load object configuration
      community.datapower.load_conf:
        domain: "{{ domain }}"
        body:
          LoadConfiguration:
            CryptoValCred:
              CRLDPHandling: ignore
              CertValidationMode: legacy
              Certificate:
                - Test1
                - Test2
              CheckDates: 'on'
              ExplicitPolicy: 'off'
              InitialPolicySet: 2.5.29.32.0
              RequireCRL: 'off'
              UseCRL: 'on'
              mAdminState: enabled
              name: valcred

