- name: 'Export a package from DataPower'
  hosts: tocdo30150
  connection: local
  vars_prompt:
    - name: ansible_user
      prompt: Enter a UserName
      private: no

    - name: ansible_httpapi_password
      prompt: Enter the Password

  vars:
    export_directory: "./packages/{{export_type}}/{{ansible_date_time.date}}-{{ansible_date_time.hour}}{{ansible_date_time.minute}}"
    export_type: service
    domain: Enterprise

  tasks:
    - name: Create export directory
      file:
        state: directory
        path: "{{ export_directory }}"
    
    - name: Export Objects (from role)
      include_role:
        name: export
      vars:
        service_name: cmis
        service_type: MultiProtocolGateway

        #UCDv2_dpExportZipPackage.sh -b /opt/IBM/ibm-ucd/agent/var/work//testMPGW_ManifestFiles -d SNAFU -w SND -s testMPGW -p ServiceOnly -o true -f true -t ${DATETIME} -l INT
