---
- name: 'Create Demo Service with Ansible!'
  hosts: dp1
  connection: local

  tasks:
    - name: get supported objects for reference
      community.datapower.config_info:
        domain: default
    
    - name: Get Access Profile
      community.datapower.get_config:
        domain: default
        class_name: AccessProfile
    