- name: 'test play'
  hosts: dp1
  connection: local
  vars: 
    ansible_connection: httpapi
    ansible_httpapi_port: 5554
    ansible_httpapi_use_ssl: yes
    ansible_network_os: community.datapower.rest_mgmt
    ansible_user: admin
    ansible_httpapi_password: admin
    ansible_httpapi_validate_certs: false
    #domain_name: defau
  tasks:
    - name: Add cert to valcred.
      community.datapower.modify:
        domain: default
        class_name: CryptoValCred
        obj_field: Certificate
        name: valcred
        body:
          Certificate:
            #value: Test2
            value: Test1
      #name: "{{ domain_name }}"
    - name: Get all Valcred
      community.datapower.get:
        domain: default
        class_name: CryptoValCred
        obj_field: Certificate
        name: valcred
        state: True
        #recursive: True
        depth: 4
        #name: "{{ domain_name }}"
    - name: Remove Certs from valcred
      community.datapower.delete:
        domain: default
        class_name: CryptoValCred
        obj_field: Certificate
        name: valcred
       