- name: 'test play'
  hosts: dp1
  connection: local
  vars:
    domain: default
  tasks:
    - name: Create the CrytpoValCred valcred
     # ignore_errors: yes
      community.datapower.create_conf:
        domain: "{{ domain }}"
        object:
          CryptoValCred:
            name: valcred
            mAdminState: enabled

    - name: Target the CryptoValCred valcred Certificate list, appending a cert
      community.datapower.mod_conf:
        domain: "{{ domain }}"
        class_name: CryptoValCred
        name: valcred
        obj_field: Certificate
        object:
          Certificate:
            - value: Test2
            
    - name: Disable the Valcred
      community.datapower.mod_conf:
        domain: "{{ domain }}"
        object:
          CryptoValCred:
            name: valcred
            mAdminState: disabled
    
    - name: Get the ValCred 
      community.datapower.get_conf:
        domain: "{{ domain }}"
        class_name: CryptoValCred
        name: valcred

    - name: Get the ValCred Certificate list
      community.datapower.get_conf:
        domain: "{{ domain }}"
        class_name: CryptoValCred
        obj_field: Certificate
        name: valcred

    - name: Delete the ValCred Certificate List
      community.datapower.del_conf:
        domain: "{{ domain }}"
        class_name: CryptoValCred
        obj_field: Certificate
        name: valcred

    - name: Get the ValCred Certificate list to prove its empty
      community.datapower.get_conf:
        domain: "{{ domain }}"
        class_name: CryptoValCred
        obj_field: Certificate
        name: valcred

    - name: Delete the ValCred
      community.datapower.del_conf:
        domain: "{{ domain }}"
        class_name: CryptoValCred
        name: valcred