- name: 'test play'
  hosts: dp1
  connection: local
  vars:
    domain: default
  tasks:
    - name: Create the CrytpoValCred valcred
     # ignore_errors: yes
      community.datapower.apply_conf:
        domain: "{{ domain }}"
        obj_name: valcred
        class_name: CryptoValCred
        overwrite: no
        config:
          CryptoValCred:
            mAdminState: enabled

    - name: Get the ValCred 
      community.datapower.get_conf:
        domain: "{{ domain }}"
        class_name: CryptoValCred
        name: valcred

    - name: Delete the ValCred Certificate List
      community.datapower.del_conf:
        domain: "{{ domain }}"
        class_name: CryptoValCred
        obj_field: Certificate
        name: valcred
