- name: 'test create_conf play'
  hosts: dp1
  connection: local
  vars:
    domain: default
  tasks:
    - name: Request example, this will return Config Items
      community.datapower.request:
        path: /mgmt/config/
        method: GET

