- name: 'test play'
  hosts: dp1
  connection: local
  vars:
    domain: default
  tasks:
    - name: Create certificate
      community.datapower.create_conf:
        domain: "{{ domain }}"
        body:
          CryptoCertificate:
            name: Test2
            mAdminState: enabled
            Filename: cert:///webgui-sscert.pem
            PasswordAlias: 'off'
            IgnoreExpiration: 'off'

    - name: Get the cert object Test2
      community.datapower.get_conf:
        domain: "{{ domain }}"
        class_name: CryptoCertificate
        name: Test2


    - name: Modify the valcred Certificate list
      community.datapower.mod_conf:
        domain: "{{ domain }}"
        class_name: CryptoValCred
        name: valcred
        obj_field: Certificate
        body:
          Certificate:
            - value: Test2
         
    - name: Delete Test2 cert
      community.datapower.del_conf:
        domain: "{{ domain }}"
        class_name: CryptoCertificate
        name: Test2

    - name: Save Domain 
      community.datapower.action:
        domain: "{{ domain }}"
        body:
          SaveConfig: {}    
    
    - name: Export object configuration
      community.datapower.export:
        domain: "{{ domain }}"
        body:
          Export:
            Format: JSON
            UserComment: comments
            AllFiles: 'off'
            Persisted: 'off'
            IncludeInternalFiles: 'off'
            Object:
              - name: valcred
                class: CryptoValCred
                
    - name: Request example, this will return Config Items
      community.datapower.request:
        path: /mgmt/config/
        method: GET
    