- name: 'test play'
  hosts: dp1
  connection: local
  vars:
    domain: default
  tasks:
    - name: Export object configuration
      community.datapower.export:
        domain: "{{ domain }}"
        body:
          Export:
            Format: JSON
            UserComment: comments
            AllFiles: 'off'
            Persisted: 'off'
            IncludeInternalFiles: 'off'
            Object:
              - name: valcred
                class: CryptoValCred
    - name: Export object config in xml format (Shows up as base64 in response payload)
      community.datapower.export:
        domain: "{{ domain }}"
        body:
          Export:
            Format: XML
            UserComment: comments
            AllFiles: 'off'
            Persisted: 'off'
            IncludeInternalFiles: 'off'
            Object:
              - name: valcred
                class: CryptoValCred
    - name: Export domain config in ZIP format.
      community.datapower.export:
        domain: "{{ domain }}"
        body:
          Export:
            Format: ZIP
            UserComment: comments
            AllFiles: 'off'
            Persisted: 'off'
            IncludeInternalFiles: 'off'


